name: "Check Pull Request"
description: "Checking PR title and PR message"
inputs:
  title-regex:
    description: "Regular expression to check PR title abd PR message"
    required: false
    default: '^FEATURE-[0-9]+: .+'

runs:
  using: "composite"
  steps:
    - name: Check PR title and body
      uses: actions/github-script@v7
      env:
        TITLE_REGEX: ${{inputs.title-regex}}
      with:
        script: |
          const pr = context.payload.pull_request;

          const title = pr.title;
          const body = pr.body || '';
          const titleRegex = new RegExp(process.env.TITLE_REGEX);

          if (!titleRegex.test(title)) {
            core.setFailed(`PR title: "${title}" doesn't match the pattern: ${titleRegex}`);
          }

          if (body.trim() === '') {
            core.setFailed('PR message shouldn't be empty');
          } else {
            core.info('PR check successful');
          }